site_name: Mohammed EL AMRANI - Portfolio
docs_dir: docs         # Point to source Markdown
site_dir: site
site_url: https://github.com/lostfsoul/moe-pf/
repo_url: https://github.com/lostfsoul/moe-pf/
edit_uri: edit/main/docs/

theme:
  name: terminal
  palette: gruvbox_dark
  font:
    text: JetBrains Mono
    code: Fira Code
  features:
    - footer.prev_next


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/yourprofile
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourhandle
    - icon: fontawesome/solid/envelope
      link: mailto:your.email@domain.com

nav:
  - Home: 'index.md'
  - About Me: 'about.md'
  - Portfolio: 
    - Expertise: expertise.md
    - AI Solutions: ai-solutions.md
    - Data Engineering: data-engineering.md
    - Projects: projects.md
    - Blog: blog.md
    - Contact: contact.md

plugins:
  - search
  - mkdocs-exclude:
      glob: [admin/.*]  # Prevent MkDocs from processing CMS files

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.snippets

  