backend:
  name: github
  repo: lostfsoul/moe-pf
  branch: main
  site_url: https://lostfsoul.github.io/moe-pf/
  base_url: /

media_folder: "docs/images/uploads"
public_folder: "/moe-pf/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "docs"     # Source directory
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
